collections:
  authors:
    output: true
  categories:
    output: true
future: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

mapbox-token: pk.eyJ1IjoibWljaGVsbGVtaG8iLCJhIjoiY2l2MWM0cWthMDA3NDJ5b3g3cGF5d2huaiJ9.2otqgGYhjK7bBnAhrnyu5A
formspree_email: geoffmichelleclimbski@gmail.com

plugins:
  - jekyll-feed

feed:
  categories:
    - done
    - upcoming